import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export default function Home({ blogs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Spacex Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="#">The Spacex App</a>
        </h1>

        <div className={styles.grid}>
          {blogs.map((blog) => {
            return (
              <>
                <a className={styles.card}>
                  <h2>{blog.node.title}</h2>
                  <p>{blog.node.excerpt}</p>
                </a>
              </>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'http://mufaqar.com/graphql',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query MyQuery {
        posts {
          edges {
            node {
              date
              id
              link
              slug
              title
              uri
              excerpt
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      blogs: data.posts.edges,
    },
  };
}
