import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export default function Home({ launches }) {
  console.log('Launches', launches);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Spacex Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://mufaqar.com">The Spacex App</a>
        </h1>

        <p className={styles.description}>
          Created By <code className={styles.code}>Mufaqar</code>
        </p>

        <div className={styles.grid}>
          {launches.map((launch) => {
            return (
              <>
                <a
                  key={launch.id}
                  href={launch.links.video_link}
                  className={styles.card}
                >
                  <h2>{launch.mission_name}</h2>
                  <p>{launch.launch_date_local}</p>
                </a>
              </>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>Powered by Next</footer>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://api.spacex.land/graphql/',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
